services:
  - type: web
    name: workshop-backend
    env: docker
    buildCommand: ""
    startCommand: ""
    plan: free
    envVars:
      - key: PORT
        value: "8081"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
